//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicBeePlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicBeePlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   jcc00456biz@gmail.com に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Track name change に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu0 {
            get {
                return ResourceManager.GetString("Menu0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zenkaku =&gt; Hankaku に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu0_0 {
            get {
                return ResourceManager.GetString("Menu0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import from text (comma) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu0_1 {
            get {
                return ResourceManager.GetString("Menu0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import from text (TAB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu0_2 {
            get {
                return ResourceManager.GetString("Menu0_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plugin to change track names に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MyDescription {
            get {
                return ResourceManager.GetString("MyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Track name change plugin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MyName {
            get {
                return ResourceManager.GetString("MyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a file to open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenFileTitle {
            get {
                return ResourceManager.GetString("OpenFileTitle", resourceCulture);
            }
        }
    }
}
